
    <m:item name='普通文章' ischannel='1' link='content_list.php?channelid=1' linkadd='article_add.php?channelid=1' channelid='1' rank='' target='main' />
  <m:item name='保留预设页面' ischannel='1' link='content_list.php?channelid=6' linkadd='archives_add.php?channelid=6' channelid='6' rank='' target='main' />
  <m:item name='关于我们' ischannel='1' link='content_list.php?channelid=17' linkadd='article_add.php?channelid=17' channelid='17' rank='' target='main' />
  <m:item name='我的服务' ischannel='1' link='content_list.php?channelid=18' linkadd='article_add.php?channelid=18' channelid='18' rank='' target='main' />
  <m:item name='慢生活' ischannel='1' link='content_list.php?channelid=19' linkadd='article_add.php?channelid=19' channelid='19' rank='' target='main' />
  <m:item name='预留页面样式2' ischannel='1' link='content_list.php?channelid=21' linkadd='article_add.php?channelid=21' channelid='21' rank='' target='main' />

  <m:item name='专题管理' ischannel='1' link='content_s_list.php' linkadd='spec_add.php' channelid='-1' rank='spec_New' target='main' />
