<field:body itemname="ÎÄÕÂÄÚÈÝ" autofield="0" notsend="0" type="htmltext" isnull="true" islist="1" default=""  maxlength="" page="split">	
</field:body>	
<field:litpic2 itemname="ËõÂÔÍ¼2" autofield="1" notsend="0" type="img" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:litpic2>
<field:background itemname="ÍøÒ³±³¾°Í¼" autofield="1" notsend="0" type="img" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:background>
<field:litpic3 itemname="ËõÂÔÍ¼3(Ê×Ò³)" autofield="1" notsend="0" type="img" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:litpic3>
