<?php
$z[0]=Array("field","",495,514);
$z[0][4]['name']="title";
$z[1]=Array("global","",515,541);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",582,604);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",644,695);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",7800,7835);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",7924,7943);
$z[5][4]['name']="title";
$z[6]=Array("field","",7974,8030);
$z[6][4]['name']="pubdate";
$z[6][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[7]=Array("field","",8147,8165);
$z[7][4]['name']="body";
$z[8]=Array("include","",8304,8342);
$z[8][4]['filename']="footer2.htm";

?>