<?php
$z[0]=Array("item","",4,77);
$z[0][4]['name']="插件管理器";
$z[0][4]['link']="plus_main.php";
$z[0][4]['rank']="10";
$z[0][4]['target']="main";
$z[1]=Array("item","",81,164);
$z[1][4]['name']="挑错管理";
$z[1][4]['link']="erraddsave.php";
$z[1][4]['rank']="plus_挑错管理";
$z[1][4]['target']="main";
$z[2]=Array("item","",166,259);
$z[2][4]['name']="文件管理器";
$z[2][4]['link']="file_manage_main.php";
$z[2][4]['rank']="plus_文件管理器";
$z[2][4]['target']="main";

?>