<?php
$z[0]=Array("field","(@me==\"\")? @me=\"cur\":@me=\"\";",280,358);
$z[0][4]['name']="typeid";
$z[0][4]['runphp']="yes";
$z[1]=Array("channel","     \r\n              <li><a href=\"[field:typeurl/]\">\r\n                <div style=\"margin-top: 0px;\">\r\n                  <p>[field:typename/]</p>\r\n                </div>\r\n                </a></li>\r\n		",528,891);
$z[1][4]['type']="top";
$z[1][4]['row']="10";
$z[1][4]['currentstyle']="<li><a href='~typelink~' class='cur'><div style='margin-top: 0px;'><p>~typename~</p></div></a></li>";
$z[2]=Array("global","",1243,1267);
$z[2][4]['name']="phone_one";

?>