<?php
$z[0]=Array("global","",420,446);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",490,520);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",557,584);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",7165,7200);
$z[3][4]['filename']="head.htm";
$z[4]=Array("arclist","\r\n            <a href=\"#\">\r\n              <div class=\"M-work-list\">\r\n                <div class=\"item6\"> <img src=\"[field:litpic3 function='GetOneImgUrl2(@me,1)'/]\" width=\"205\" height=\"205\" />\r\n                  <div class=\"cornerCC\"> </div>\r\n                  <dl>\r\n                    <dd><font color=\"#ECE9E7\">[field:title/]</font></dd>\r\n                  </dl>\r\n                </div>\r\n              </div>\r\n              </a> \r\n              ",13325,13865);
$z[4][4]['row']="7";
$z[4][4]['titlelen']="32";
$z[4][4]['typeid']="3";
$z[4][4]['addfields']="litpic3";
$z[4][4]['channelid']="19";
$z[5]=Array("type","[field:typelink /]",14354,14406);
$z[5][4]['typeid']="9";
$z[6]=Array("arclist","\r\n     \r\n        <div class=\"ss-row ss-medium\">\r\n          <div class=\"ss-left\"> <a href=\"#\" class=\"ss-circle ss-circle-1\"><img src=\"/dedemao/images/new-ico1.png\"></a> </div>\r\n          <div class=\"ss-right\">\r\n            <h3> <span><a href=\"[field:arcurl/]\">[field:fulltitle/]</a></span> <a href=\"[field:arcurl/]\">[field:description function='cn_substr(@me,100)'/]...</a> </h3>\r\n          </div>\r\n        </div>\r\n        ",18133,18608);
$z[6][4]['typeid']="10";
$z[6][4]['limit']="0,1";
$z[7]=Array("arclist","\r\n<div class=\"ss-row ss-large\">\r\n          <div class=\"ss-left\">\r\n            <h3> <span><a href=\"[field:arcurl/]\">[field:fulltitle/]</a></span> <a href=\"[field:arcurl/]\">[field:description function='cn_substr(@me,100)'/]...</a> </h3>\r\n          </div>\r\n          <div class=\"ss-right\"> <a href=\"#\" class=\"ss-circle ss-circle-2\"><img src=\"/dedemao/images/new-ico1.png\"></a> </div>\r\n        </div>        \r\n",18613,19072);
$z[7][4]['typeid']="10";
$z[7][4]['limit']="1,1";
$z[8]=Array("arclist","\r\n     \r\n        <div class=\"ss-row ss-medium\">\r\n          <div class=\"ss-left\"> <a href=\"#\" class=\"ss-circle ss-circle-1\"><img src=\"/dedemao/images/new-ico1.png\"></a> </div>\r\n          <div class=\"ss-right\">\r\n            <h3> <span><a href=\"[field:arcurl/]\">[field:fulltitle/]</a></span> <a href=\"[field:arcurl/]\">[field:description function='cn_substr(@me,100)'/]...</a> </h3>\r\n          </div>\r\n        </div>\r\n        ",19081,19556);
$z[8][4]['typeid']="10";
$z[8][4]['limit']="2,1";
$z[9]=Array("arclist","\r\n<div class=\"ss-row ss-large\">\r\n          <div class=\"ss-left\">\r\n            <h3> <span><a href=\"[field:arcurl/]\">[field:fulltitle/]</a></span> <a href=\"[field:arcurl/]\">[field:description function='cn_substr(@me,100)'/]...</a> </h3>\r\n          </div>\r\n          <div class=\"ss-right\"> <a href=\"#\" class=\"ss-circle ss-circle-2\"><img src=\"/dedemao/images/new-ico1.png\"></a> </div>\r\n        </div>        \r\n",19561,20020);
$z[9][4]['typeid']="10";
$z[9][4]['limit']="3,1";
$z[10]=Array("arclist","\r\n     \r\n        <div class=\"ss-row ss-medium\">\r\n          <div class=\"ss-left\"> <a href=\"#\" class=\"ss-circle ss-circle-1\"><img src=\"/dedemao/images/new-ico1.png\"></a> </div>\r\n          <div class=\"ss-right\">\r\n            <h3> <span><a href=\"[field:arcurl/]\">[field:fulltitle/]</a></span> <a href=\"[field:arcurl/]\">[field:description function='cn_substr(@me,100)'/]...</a> </h3>\r\n          </div>\r\n        </div>\r\n        ",20030,20505);
$z[10][4]['typeid']="10";
$z[10][4]['limit']="4,1";
$z[11]=Array("type","[field:typelink /]",20530,20583);
$z[11][4]['typeid']="10";
$z[12]=Array("include","",21391,21428);
$z[12][4]['filename']="footer.htm";

?>