<?php
$z[0]=Array("field","",495,518);
$z[0][4]['name']="seotitle";
$z[1]=Array("global","",519,545);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",586,615);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",655,713);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",7846,7881);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",14482,14520);
$z[5][4]['filename']="footer2.htm";

?>