<?php
$z[0]=Array("field","",494,517);
$z[0][4]['name']="seotitle";
$z[1]=Array("global","",518,544);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",585,614);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",654,712);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",7334,7369);
$z[4][4]['filename']="head.htm";
$z[5]=Array("type","[field:typelink /]",9121,9173);
$z[5][4]['typeid']="4";
$z[6]=Array("type","[field:typelink /]",9575,9627);
$z[6][4]['typeid']="5";
$z[7]=Array("type","[field:typelink /]",10030,10082);
$z[7][4]['typeid']="7";
$z[8]=Array("type","[field:typelink /]",10492,10544);
$z[8][4]['typeid']="8";
$z[9]=Array("include","",13594,13632);
$z[9][4]['filename']="footer3.htm";
$z[10]=Array("global","",14962,14983);
$z[10][4]['name']="tongji";

?>