<?php
$z[0]=Array("field","",496,519);
$z[0][4]['name']="seotitle";
$z[1]=Array("global","",520,546);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",587,616);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",656,714);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",7330,7365);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",16170,16208);
$z[5][4]['filename']="footer3.htm";
$z[6]=Array("global","",16246,16267);
$z[6][4]['name']="tongji";

?>