<?php
$z[0]=Array("field","",492,515);
$z[0][4]['name']="seotitle";
$z[1]=Array("global","",516,542);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",583,612);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",652,710);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",7783,7818);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",13723,13761);
$z[5][4]['filename']="footer2.htm";
$z[6]=Array("global","",14956,14977);
$z[6][4]['name']="tongji";

?>