<?php
$z[0]=Array("global","",520,550);
$z[0][4]['name']="cfg_description";
$z[1]=Array("global","",587,614);
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("include","",8748,8783);
$z[2][4]['filename']="head.htm";
$z[3]=Array("arclist","\r\n            <a href=\"#\">\r\n              <div class=\"M-work-list\">\r\n                <div class=\"item6\"> <img src=\"[field:litpic3 function='GetOneImgUrl2(@me,1)'/]\" width=\"205\" height=\"205\" />\r\n                  <div class=\"cornerCC\"> </div>\r\n                  <dl>\r\n                    <dd><font color=\"#ECE9E7\">[field:title/]</font></dd>\r\n                  </dl>\r\n                </div>\r\n              </div>\r\n              </a> \r\n              ",17999,18540);
$z[3][4]['row']="7";
$z[3][4]['titlelen']="32";
$z[3][4]['typeid']="24";
$z[3][4]['addfields']="litpic3";
$z[3][4]['channelid']="19";
$z[4]=Array("type","[field:typelink /]",19040,19092);
$z[4][4]['typeid']="9";
$z[5]=Array("arclist","\r\n     \r\n        <div class=\"ss-row ss-medium\">\r\n          <div class=\"ss-left\"> <a href=\"#\" class=\"ss-circle ss-circle-1\"><img src=\"/dedemao/images/new-ico1.png\"></a> </div>\r\n          <div class=\"ss-right\">\r\n            <h3> <span><a href=\"[field:arcurl/]\">[field:fulltitle/]</a></span> <a href=\"[field:arcurl/]\">[field:description function='cn_substr(@me,100)'/]...</a> </h3>\r\n          </div>\r\n        </div>\r\n        ",19746,20220);
$z[5][4]['typeid']="3";
$z[5][4]['limit']="0,1";
$z[6]=Array("arclist","\r\n<div class=\"ss-row ss-large\">\r\n          <div class=\"ss-left\">\r\n            <h3> <span><a href=\"[field:arcurl/]\">[field:fulltitle/]</a></span> <a href=\"[field:arcurl/]\">[field:description function='cn_substr(@me,100)'/]...</a> </h3>\r\n          </div>\r\n          <div class=\"ss-right\"> <a href=\"#\" class=\"ss-circle ss-circle-2\"><img src=\"/dedemao/images/new-ico1.png\"></a> </div>\r\n        </div>        \r\n",20225,20683);
$z[6][4]['typeid']="3";
$z[6][4]['limit']="1,1";
$z[7]=Array("arclist","\r\n     \r\n        <div class=\"ss-row ss-medium\">\r\n          <div class=\"ss-left\"> <a href=\"#\" class=\"ss-circle ss-circle-1\"><img src=\"/dedemao/images/new-ico1.png\"></a> </div>\r\n          <div class=\"ss-right\">\r\n            <h3> <span><a href=\"[field:arcurl/]\">[field:fulltitle/]</a></span> <a href=\"[field:arcurl/]\">[field:description function='cn_substr(@me,100)'/]...</a> </h3>\r\n          </div>\r\n        </div>\r\n        ",20692,21166);
$z[7][4]['typeid']="3";
$z[7][4]['limit']="2,1";
$z[8]=Array("arclist","\r\n<div class=\"ss-row ss-large\">\r\n          <div class=\"ss-left\">\r\n            <h3> <span><a href=\"[field:arcurl/]\">[field:fulltitle/]</a></span> <a href=\"[field:arcurl/]\">[field:description function='cn_substr(@me,100)'/]...</a> </h3>\r\n          </div>\r\n          <div class=\"ss-right\"> <a href=\"#\" class=\"ss-circle ss-circle-2\"><img src=\"/dedemao/images/new-ico1.png\"></a> </div>\r\n        </div>        \r\n",21171,21629);
$z[8][4]['typeid']="3";
$z[8][4]['limit']="3,1";
$z[9]=Array("arclist","\r\n     \r\n        <div class=\"ss-row ss-medium\">\r\n          <div class=\"ss-left\"> <a href=\"#\" class=\"ss-circle ss-circle-1\"><img src=\"/dedemao/images/new-ico1.png\"></a> </div>\r\n          <div class=\"ss-right\">\r\n            <h3> <span><a href=\"[field:arcurl/]\">[field:fulltitle/]</a></span> <a href=\"[field:arcurl/]\">[field:description function='cn_substr(@me,100)'/]...</a> </h3>\r\n          </div>\r\n        </div>\r\n        ",21639,22113);
$z[9][4]['typeid']="3";
$z[9][4]['limit']="4,1";
$z[10]=Array("type","[field:typelink /]",22138,22191);
$z[10][4]['typeid']="10";
$z[11]=Array("include","",22999,23036);
$z[11][4]['filename']="footer.htm";

?>