<?php
$z[0]=Array("field","",484,507);
$z[0][4]['name']="seotitle";
$z[1]=Array("global","",508,534);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",574,603);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",642,700);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",7560,7595);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",14453,14491);
$z[5][4]['filename']="footer2.htm";
$z[6]=Array("global","",15629,15650);
$z[6][4]['name']="tongji";

?>